config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :user_options
  get 'search', to: 'users#search'

  resources :messages
  resources :rooms
  # Routing for budget section
  resources :budgets do
    resources :groups do
      resources :categories
    end
  end
  #routing for post with likes and comments 
  resources :posts do 
    resources :likes
    resources :comments
  end
  
  resources :socials
  resources :mentions, only: [:index]
  resources :mentioned_posts, only: [:index]
  resources :follows
  resources :followers, only: [:index]
  resources :followings, only: [:index]


  resources :accounts
  resources :goals
  
  resources :retirements
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#show', as: 'user'
  resources :calculate_debts
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> BudgetBuddy</span>
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= "BudgetBuddy" %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_menu.html.erb
<% flash.each do |key, value| %>
  <div>
    <%= value %>
  </div>
<% end %>

<% if user_signed_in? %>
  <p>Signed in as <%= current_user.name %> | <%= link_to 'log out', destroy_user_session_path, method: :delete %></p>
<% end %>
<ul>
  <li><%= link_to 'Home', root_path %></li>
</ul>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light ">
  <div class="container ">
    <%= link_to "BudgetBuddy", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <!--- Navbar's search bar -->
      <div style="padding-right: 150px">
        <% if user_signed_in? %>
          <form class="form-inline my-2 my-lg-0" action="/search">
            <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search for a user" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        <% end %>
      </div>
      <ul class="navbar-nav">
        <% if user_signed_in? %>

          <li class="blank"><p></p></li>
          <li class="nav-item"><%= link_to "Budget", budgets_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Goals", goals_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Retirement", retirements_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Debt Calculator ", calculate_debts_path, class: "nav-link" %></li>


          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.present? %>
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <% if current_user.avatar.attached?%>
                <img class="rounded-circle" height= "20" width="20" <%=image_tag(current_user.avatar)%>
              <% else %>
                <img class="rounded-circle" height= "20" width="20" <%=image_tag("No_user.jpg")%>
              <%end %>
            <% end %>
            <% end %>

            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">

              <% if current_user.admin? && respond_to?(:admin_root_path) %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>

              <%= link_to "My Post", posts_url, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>

              <%= link_to "Accounts", accounts_url, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>


              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>

              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<!-- Vertical navbar -->
  <%= render 'shared/head' %> 
  
  <% if current_user.present? %>
    <nav class="sidenav vertical-nav bg-white" id="sidebar">
            <div class="py-4 px-3 mb-4 bg-light">
                <div class="media d-flex align-items-center">
                    <% if current_user.avatar.attached?%>
                        <img class="rounded-circle" height= "65" width="65" <%=image_tag(current_user.avatar)%>
                    <% else %>
                        <img class="rounded-circle" height= "65" width="65" <%=image_tag("No_user.jpg")%>
                    <% end %>
                        <div class="display: flex; justify-content: flex-end">
                            <h4 class="m-0"><%=current_user.first_name%> <%=current_user.last_name %></h4>
                            <p class="font-weight-light text-muted mb-0"><%=current_user.email%></p>
                        </div>
                </div>
            </div>

            <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0">Main</p>

            <ul class="nav flex-column bg-white mb-0 ">
                <li class="nav-item">
                    <a href="<%= root_path %>" class="nav-link text-dark font-italic">
                        <i class="fa fa-home mr-3 text-primary fa-fw"></i>
                            Social Home
                        </a>
                </li>
                <li class="nav-item">
                    <a href="<%= mentioned_posts_path %>" class="nav-link text-dark font-italic">
                        <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
                            Mentions
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link text-dark font-italic">
                        <i class="fa fa-inbox mr-3 text-primary fa-fw"></i>
                            Messages
                    </a>
                </li>
                <li class="nav-item ">
                    <a href="<%= user_path(current_user) %>" class="nav-link text-dark font-italic">
                        <i class="fa fa-picture-o mr-3 text-primary fa-fw"></i>
                            My Profile 
                    </a>
                </li>
                <li class="nav-item ">
                    <a href="<%= users_path %>" class="nav-link text-dark font-italic">
                        <i class="fa fa-users mr-3 text-primary fa-fw"></i>
                            Users 
                    </a>
                </li>
                
            </ul>


        </nav>     
    <% end %>
   
<!-- End vertical navbar -->