config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :user_options
  get 'search', to: 'users#search'

  resources :messages
  resources :rooms
  # Routing for budget section
  resources :budgets do
    resources :groups do
      resources :categories
    end
  end
  #routing for post with likes and comments 
  resources :posts do 
    resources :likes
    resources :comments
  end
  
  resources :socials
  resources :mentions, only: [:index]
  resources :mentioned_posts, only: [:index]
  resources :follows
  resources :followers, only: [:index]
  resources :followings, only: [:index]


  resources :accounts
  resources :goals
  
  resources :retirements
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#show', as: 'user'
  resources :calculate_debts
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!

  # GET /followers
  # GET /followers.json
  def index
    theId = params[:id]
    @user = User.find(theId)
    @followers = Follow.where(following:theId).pluck(:requestor)
  end

end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_with(model: follower, local: true) do |form| %>
  <% if follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% follower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% if follower.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', follower, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if follower.persisted? %>
      <%= link_to "Cancel", follower, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", followers_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/followers/index.html.erb

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "userpop" %>

    <style>
      h2 {text-align: center;}
    </style>

    
    <h2><%=link_to  user_path(@user) do %><%=@user.name%> <% end %> Followers</h2>

    <section class="our-webcoderskull padding-lg">
      <div class="container">
        <ul class="row">
        <% @followers.each do |user| %>
          <% user = User.find(user)%>
          <li class="col-12 col-md-6 col-lg-3">
              <div class="cnt-block equal-hight" style="height: 349px;">
              <% if user.avatar.attached?%>
                <div class="avatar">
                    <%= image_tag(user.avatar, class: 'img-circular') %>
                </div>
              <% else %>
              <div class="avatar">
                <%= image_tag("No_user.jpg", class: 'img-circular') %>
                </div>
              <%end%>

                <h3><%=user.first_name%> <%=user.last_name %></h3>
                <p><%= (user.email) %></p>
                <ul class="follow-us clearfix">
                <% if Follow.where(:requestor => user.id, :following =>current_user.id).present? && Follow.where(:requestor => current_user.id, :following =>user.id).present?%> 
                  <h7><mark>Follow Each Other</mark></h7>
                  <% elsif Follow.where(:requestor => user.id, :following =>current_user.id).present? %>
                  <h7><mark>Follows You</mark></h7>
                <%end %>
                </ul>
               <h3> <%= link_to 'View Profile', user %> </h3>
              </div>
          </li>
          <% end %>
      
        </ul>
      </div>
    </section>